apiVersion: v1
kind: Deployment
metadata:
  name: nodeapi
spec:
  replicas: 2
  template:
    metadata:
      name: nodeapi
      labels:
        app: nodeapi
    spec:
      containers:
      - image: nodeapi:70
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
spec:
  type: LoadBalancer
  externalIPs:
  - 10.96.0.1
  selector:
    app: nodeapi
  ports:
  - port: 8081
    targetPort: 6443